name: dart_uploader
description: A dart library that aids in offloading file uploading to background isolate and gives task updates to main isolate in a reactive way.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  mime: ^1.0.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.3.2

flutter:
